# .golangci.yml
linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - errcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

linters-settings:
  govet:
    check-shadowing: true
issues:
  exclude-use-default: false